const defaultProducts = [
  {
    "id": "1",
    "name": "عرض 1 كيلو زيت زيتون + ربع هدية",
    "category": "offers",
    "price": 500,
    "oldPrice": 650,
    "discount": 23,
    "weight": "1.25 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.9
  },
  {
    "id": "2",
    "name": "عرض 3 صابون طبيعي + 1 هدية",
    "category": "offers",
    "price": 210,
    "oldPrice": 280,
    "discount": 25,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.5
  },
  {
    "id": "3",
    "name": "باكيت كِش كِنج الهندي الأصلي (شامبو + زيت)",
    "category": "offers",
    "price": 450,
    "oldPrice": 600,
    "discount": 25,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/f658331686324b04af68879283017f68.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.8
  },
  {
    "id": "4",
    "name": "عرض منتجات سيوة",
    "category": "offers",
    "price": 500,
    "oldPrice": 750,
    "discount": 33,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.4
  },
  {
    "id": "5",
    "name": "زيت زيتون بكر ممتاز (الوادي) ½ زجاج غامق - عرض 3+1 هدية",
    "category": "offers",
    "price": 840,
    "oldPrice": 1120,
    "discount": 25,
    "weight": "2 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.4
  },
  {
    "id": "6",
    "name": "عرض مجموعة لبان الذكر للعناية بالبشرة",
    "category": "offers",
    "price": 200,
    "oldPrice": 320,
    "discount": 38,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.7
  },
  {
    "id": "7",
    "name": "مجموعة التغذية العميقة",
    "category": "offers",
    "price": 300,
    "oldPrice": 350,
    "discount": 14,
    "weight": "60 مل",
    "image": "https://karimolive.shop/uploads/products/images/2bfc6c0997204586acfe25200e44b9b1.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.2
  },
  {
    "id": "8",
    "name": "مجموعة الترميم الشامل",
    "category": "offers",
    "price": 410,
    "oldPrice": 490,
    "discount": 16,
    "weight": "60 مل",
    "image": "https://karimolive.shop/uploads/products/images/449a7ee890274cadbc02125852729d7c.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.6
  },
  {
    "id": "9",
    "name": "المجموعة الذهبية",
    "category": "offers",
    "price": 490,
    "oldPrice": 630,
    "discount": 22,
    "weight": "60 مل",
    "image": "https://karimolive.shop/uploads/products/images/d715edf4a6e34c92a308673bc72e80d5.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.7
  },
  {
    "id": "10",
    "name": "مجموعة الإشراقة السريعة",
    "category": "offers",
    "price": 190,
    "oldPrice": 210,
    "discount": 10,
    "weight": "60 مل",
    "image": "https://karimolive.shop/uploads/products/images/a1db9e89db554ecfa81b1ca2d51e3322.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.1
  },
  {
    "id": "11",
    "name": "مجموعتين زيوت (تساقط + إنبات) + ديرما رولر هدية",
    "category": "offers",
    "price": 400,
    "oldPrice": 0,
    "discount": 0,
    "weight": "150 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": false,
    "origin": "",
    "rating": 4.1
  },
  {
    "id": "12",
    "name": "مجموعتين زيوت (تساقط + إنبات) + ربع سدر مطحون هدية",
    "category": "offers",
    "price": 400,
    "oldPrice": 450,
    "discount": 11,
    "weight": "150 مل",
    "image": "https://karimolive.shop/uploads/products/images/9af0c333c0a84136b18969afbb3f05cb.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.6
  },
  {
    "id": "13",
    "name": "مجموعة الخطير 2 لفراغات الشعر - حجم صغير",
    "category": "hair_oils",
    "price": 200,
    "oldPrice": 280,
    "discount": 29,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.2
  },
  {
    "id": "14",
    "name": "مجموعة الخطير 1 لتساقط الشعر",
    "category": "hair_oils",
    "price": 200,
    "oldPrice": 280,
    "discount": 29,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.8
  },
  {
    "id": "15",
    "name": "مجموعة منير الخطير 2 - حجم كبير",
    "category": "hair_oils",
    "price": 280,
    "oldPrice": 320,
    "discount": 12,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/fd3a601c885945d2b56e578300d7ccd5.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 5
  },
  {
    "id": "16",
    "name": "زيت الحية الباكستاني الأصلي",
    "category": "hair_oils",
    "price": 250,
    "oldPrice": 300,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/42b1cb5385254cd19807a6e695177119.webp",
    "available": true,
    "origin": "باكستان",
    "rating": 3.6
  },
  {
    "id": "17",
    "name": "زيت الكركار السوداني",
    "category": "hair_oils",
    "price": 150,
    "oldPrice": 180,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/535a9ad3311646c28253c2acfce5d4b0.webp",
    "available": true,
    "origin": "السودان",
    "rating": 4.8
  },
  {
    "id": "18",
    "name": "سيروم لوريال الذهبي للشعر",
    "category": "hair_oils",
    "price": 250,
    "oldPrice": 300,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/047fd2c0c79d48b282e3beffef99217a.webp",
    "available": true,
    "origin": "فرنسا",
    "rating": 4.2
  },
  {
    "id": "19",
    "name": "زيت شعر Herbs India - أعشاب الهند",
    "category": "hair_oils",
    "price": 120,
    "oldPrice": 180,
    "discount": 33,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.3
  },
  {
    "id": "20",
    "name": "زيت 108 عشبة الهندي الأصلي",
    "category": "hair_oils",
    "price": 1100,
    "oldPrice": 1500,
    "discount": 27,
    "weight": "500 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4
  },
  {
    "id": "21",
    "name": "زيت الأرجان الإماراتي",
    "category": "hair_oils",
    "price": 150,
    "oldPrice": 200,
    "discount": 25,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الإمارات",
    "rating": 4.2
  },
  {
    "id": "22",
    "name": "زيت الحية المطور",
    "category": "hair_oils",
    "price": 300,
    "oldPrice": 350,
    "discount": 14,
    "weight": "300 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.1
  },
  {
    "id": "23",
    "name": "مجموعة الزيوت العشبية Herbal Oil",
    "category": "hair_oils",
    "price": 150,
    "oldPrice": 200,
    "discount": 25,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.9
  },
  {
    "id": "24",
    "name": "زيت الحشيش الأفغاني",
    "category": "hair_oils",
    "price": 300,
    "oldPrice": 350,
    "discount": 14,
    "weight": "300 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.8
  },
  {
    "id": "25",
    "name": "زيت تارا بالياسمين الهندي",
    "category": "hair_oils",
    "price": 200,
    "oldPrice": 250,
    "discount": 20,
    "weight": "200 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.5
  },
  {
    "id": "26",
    "name": "زيت الأرجان المغربي الأصلي",
    "category": "hair_oils",
    "price": 300,
    "oldPrice": 350,
    "discount": 14,
    "weight": "300 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.7
  },
  {
    "id": "27",
    "name": "زيت جدايل عبدالصمد القرشي",
    "category": "hair_oils",
    "price": 250,
    "oldPrice": 300,
    "discount": 17,
    "weight": "250 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السعودية",
    "rating": 4.3
  },
  {
    "id": "28",
    "name": "زيت دابر أملا",
    "category": "hair_oils",
    "price": 120,
    "oldPrice": 150,
    "discount": 20,
    "weight": "200 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.6
  },
  {
    "id": "29",
    "name": "سيروم زيت الزيتون الاحترافي Olive Oil Serum",
    "category": "hair_oils",
    "price": 200,
    "oldPrice": 250,
    "discount": 20,
    "weight": "125 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الإمارات",
    "rating": 4.7
  },
  {
    "id": "30",
    "name": "زيت جوز الهند باراشوت الهندي",
    "category": "hair_oils",
    "price": 150,
    "oldPrice": 180,
    "discount": 17,
    "weight": "175 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.7
  },
  {
    "id": "31",
    "name": "زيت سانسار للعناية بالشعر",
    "category": "hair_oils",
    "price": 250,
    "oldPrice": 300,
    "discount": 17,
    "weight": "200 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.5
  },
  {
    "id": "32",
    "name": "زيت أوراق السدر - تركيبة 10 زيوت",
    "category": "hair_oils",
    "price": 225,
    "oldPrice": 250,
    "discount": 10,
    "weight": "125 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "",
    "rating": 3.8
  },
  {
    "id": "33",
    "name": "زيت زيتون كريم - سوبر إكسترا فرجن (1 كجم)",
    "category": "olive",
    "price": 500,
    "oldPrice": 600,
    "discount": 17,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.1
  },
  {
    "id": "34",
    "name": "زيت زيتون كريم - سوبر إكسترا فرجن (500 جم)",
    "category": "olive",
    "price": 280,
    "oldPrice": 340,
    "discount": 18,
    "weight": "500 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.7
  },
  {
    "id": "35",
    "name": "زيت زيتون كريم - سوبر إكسترا فرجن (250 جم)",
    "category": "olive",
    "price": 150,
    "oldPrice": 200,
    "discount": 25,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4
  },
  {
    "id": "36",
    "name": "زيت زيتون بكر خام - جركن 1 لتر",
    "category": "olive",
    "price": 400,
    "oldPrice": 450,
    "discount": 11,
    "weight": "1 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.2
  },
  {
    "id": "37",
    "name": "زيت زيتون بكر خام - جركن ½ لتر",
    "category": "olive",
    "price": 210,
    "oldPrice": 250,
    "discount": 16,
    "weight": "0.5 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4
  },
  {
    "id": "38",
    "name": "زيت زيتون بكر خام - جركن ¼ لتر",
    "category": "olive",
    "price": 110,
    "oldPrice": 125,
    "discount": 12,
    "weight": "0.25 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.4
  },
  {
    "id": "39",
    "name": "زيت زيتون بكر ممتاز (الوادي) - زجاج غامق ¼ لتر",
    "category": "olive",
    "price": 150,
    "oldPrice": 170,
    "discount": 12,
    "weight": "0.25 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.7
  },
  {
    "id": "40",
    "name": "زيت زيتون بكر ممتاز (الوادي) - بلاستيك 1 لتر",
    "category": "olive",
    "price": 450,
    "oldPrice": 500,
    "discount": 10,
    "weight": "1 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.6
  },
  {
    "id": "41",
    "name": "زيت زيتون بكر ممتاز (الوادي) - بلاستيك ½ لتر",
    "category": "olive",
    "price": 240,
    "oldPrice": 280,
    "discount": 14,
    "weight": "0.5 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4
  },
  {
    "id": "42",
    "name": "زيت زيتون بكر ممتاز (الوادي) - زجاج غامق 1 لتر",
    "category": "olive",
    "price": 500,
    "oldPrice": 550,
    "discount": 9,
    "weight": "1 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.7
  },
  {
    "id": "43",
    "name": "زيت زيتون بكر ممتاز (الوادي) - زجاج غامق ½ لتر",
    "category": "olive",
    "price": 280,
    "oldPrice": 300,
    "discount": 7,
    "weight": "0.5 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.9
  },
  {
    "id": "44",
    "name": "زيت زيتون عجيبة (1 لتر)",
    "category": "olive",
    "price": 550,
    "oldPrice": 650,
    "discount": 15,
    "weight": "1 لتر",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.2
  },
  {
    "id": "45",
    "name": "زيت زيتون الشعر - أوليفيا",
    "category": "olive",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.3
  },
  {
    "id": "46",
    "name": "صابونة النيلة الزرقاء",
    "category": "soap",
    "price": 70,
    "oldPrice": 90,
    "discount": 22,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 3.7
  },
  {
    "id": "47",
    "name": "صابونة لبان الذكر للتجاعيد",
    "category": "soap",
    "price": 70,
    "oldPrice": 90,
    "discount": 22,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.2
  },
  {
    "id": "48",
    "name": "صابونة زبدة الشيا لتنعيم البشرة",
    "category": "soap",
    "price": 70,
    "oldPrice": 90,
    "discount": 22,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.2
  },
  {
    "id": "49",
    "name": "صابونة العرقسوس لتفتيح البشرة",
    "category": "soap",
    "price": 70,
    "oldPrice": 90,
    "discount": 22,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.8
  },
  {
    "id": "50",
    "name": "صابونة الفحم لحب الشباب",
    "category": "soap",
    "price": 70,
    "oldPrice": 90,
    "discount": 22,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4
  },
  {
    "id": "51",
    "name": "صابونة جوز الهند والجليسرين",
    "category": "soap",
    "price": 70,
    "oldPrice": 90,
    "discount": 22,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.2
  },
  {
    "id": "52",
    "name": "صابونة العسل والكركم",
    "category": "soap",
    "price": 70,
    "oldPrice": 80,
    "discount": 13,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.1
  },
  {
    "id": "53",
    "name": "صابونة الروزماري",
    "category": "soap",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.5
  },
  {
    "id": "54",
    "name": "صابونة الشبة",
    "category": "soap",
    "price": 70,
    "oldPrice": 90,
    "discount": 22,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.9
  },
  {
    "id": "55",
    "name": "صابونة زيت الزيتون",
    "category": "soap",
    "price": 40,
    "oldPrice": 50,
    "discount": 20,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.8
  },
  {
    "id": "56",
    "name": "صابونة لبن الحمار",
    "category": "soap",
    "price": 60,
    "oldPrice": 70,
    "discount": 14,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "الصين",
    "rating": 4.2
  },
  {
    "id": "57",
    "name": "صابونة لبن الماعز",
    "category": "soap",
    "price": 60,
    "oldPrice": 70,
    "discount": 14,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "الصين",
    "rating": 4.5
  },
  {
    "id": "58",
    "name": "صابونة الكبريت",
    "category": "soap",
    "price": 60,
    "oldPrice": 70,
    "discount": 14,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "الصين",
    "rating": 4.5
  },
  {
    "id": "59",
    "name": "صابون العكر الفاسي (6 قطع)",
    "category": "soap",
    "price": 140,
    "oldPrice": 160,
    "discount": 13,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "سوريا",
    "rating": 4.1
  },
  {
    "id": "60",
    "name": "صابونة حليب الإبل",
    "category": "soap",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 3.6
  },
  {
    "id": "61",
    "name": "صابونة الغار",
    "category": "soap",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.8
  },
  {
    "id": "62",
    "name": "صابونة حبة البركة",
    "category": "soap",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 5
  },
  {
    "id": "63",
    "name": "صابونة بدوية بالعرقسوس",
    "category": "soap",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.5
  },
  {
    "id": "64",
    "name": "صابونة بدوية بالفحم",
    "category": "soap",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.3
  },
  {
    "id": "65",
    "name": "صابونة شجرة الشاي",
    "category": "soap",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/dfe4c89c8d3e4d4e863a1d09c9bd67c8.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.1
  },
  {
    "id": "66",
    "name": "كحل هاشمي أسود",
    "category": "cosmetics",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "إيران",
    "rating": 4.3
  },
  {
    "id": "67",
    "name": "مخمرية الخنجر",
    "category": "cosmetics",
    "price": 60,
    "oldPrice": 80,
    "discount": 25,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السعودية",
    "rating": 3.9
  },
  {
    "id": "68",
    "name": "عطور الخليج",
    "category": "cosmetics",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الإمارات",
    "rating": 3.8
  },
  {
    "id": "69",
    "name": "طمي مغربي بودر",
    "category": "cosmetics",
    "price": 70,
    "oldPrice": 90,
    "discount": 22,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "المغرب",
    "rating": 3.7
  },
  {
    "id": "70",
    "name": "معجون أسنان مسواك",
    "category": "cosmetics",
    "price": 50,
    "oldPrice": 70,
    "discount": 29,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السعودية",
    "rating": 4.3
  },
  {
    "id": "71",
    "name": "مخمرية العود الملكي",
    "category": "cosmetics",
    "price": 40,
    "oldPrice": 50,
    "discount": 20,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.7
  },
  {
    "id": "72",
    "name": "مخمرية للشعر والجسم",
    "category": "cosmetics",
    "price": 60,
    "oldPrice": 80,
    "discount": 25,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.2
  },
  {
    "id": "73",
    "name": "زيت مساج تايلاندي",
    "category": "cosmetics",
    "price": 120,
    "oldPrice": 150,
    "discount": 20,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "تايلاند",
    "rating": 4.2
  },
  {
    "id": "74",
    "name": "حمام كريم ناتشورال بالكولاجين",
    "category": "cosmetics",
    "price": 180,
    "oldPrice": 220,
    "discount": 18,
    "weight": "1000 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الأردن",
    "rating": 3.7
  },
  {
    "id": "75",
    "name": "جل الصبار الكوري",
    "category": "cosmetics",
    "price": 250,
    "oldPrice": 300,
    "discount": 17,
    "weight": "300 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "كوريا",
    "rating": 4.9
  },
  {
    "id": "76",
    "name": "الصابون المغربي بزيت الزيتون",
    "category": "cosmetics",
    "price": 120,
    "oldPrice": 150,
    "discount": 20,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "المغرب",
    "rating": 4.1
  },
  {
    "id": "77",
    "name": "نخاع أنثى الجمل الأصلي",
    "category": "cosmetics",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.1
  },
  {
    "id": "78",
    "name": "لوشن مرطب LAREEN",
    "category": "cosmetics",
    "price": 100,
    "oldPrice": 140,
    "discount": 29,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الإمارات",
    "rating": 3.6
  },
  {
    "id": "79",
    "name": "مقشر الوجه والجسم Lvymilla",
    "category": "cosmetics",
    "price": 100,
    "oldPrice": 140,
    "discount": 29,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الإمارات",
    "rating": 4.6
  },
  {
    "id": "80",
    "name": "كريم مسك الطهارة",
    "category": "cosmetics",
    "price": 60,
    "oldPrice": 0,
    "discount": 0,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": false,
    "origin": "",
    "rating": 4.8
  },
  {
    "id": "81",
    "name": "جل العرقسوس",
    "category": "cosmetics",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "المغرب",
    "rating": 3.8
  },
  {
    "id": "82",
    "name": "كريم لبان الذكر (خاص بالتصدير)",
    "category": "cosmetics",
    "price": 80,
    "oldPrice": 120,
    "discount": 33,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "",
    "rating": 3.6
  },
  {
    "id": "83",
    "name": "زيت مساج (قابل للتذوق)",
    "category": "cosmetics",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.7
  },
  {
    "id": "84",
    "name": "شامبو كِش كِنج الهندي الأصلي",
    "category": "cosmetics",
    "price": 225,
    "oldPrice": 250,
    "discount": 10,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/f658331686324b04af68879283017f68.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.7
  },
  {
    "id": "85",
    "name": "ليفة مغربي أصلي",
    "category": "cosmetics",
    "price": 60,
    "oldPrice": 80,
    "discount": 25,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "المغرب",
    "rating": 4.8
  },
  {
    "id": "86",
    "name": "تمر بشاير سيوة",
    "category": "dates",
    "price": 60,
    "oldPrice": 80,
    "discount": 25,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.2
  },
  {
    "id": "87",
    "name": "رطب سيوي فاخر",
    "category": "dates",
    "price": 70,
    "oldPrice": 80,
    "discount": 13,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.1
  },
  {
    "id": "88",
    "name": "رطب القصيم السكري",
    "category": "dates",
    "price": 180,
    "oldPrice": 200,
    "discount": 10,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السعودية",
    "rating": 5
  },
  {
    "id": "89",
    "name": "تمر سيوي بالسمسم بدون نوى",
    "category": "dates",
    "price": 80,
    "oldPrice": 120,
    "discount": 33,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.8
  },
  {
    "id": "90",
    "name": "تمر سيوي بالسمسم",
    "category": "dates",
    "price": 80,
    "oldPrice": 110,
    "discount": 27,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.1
  },
  {
    "id": "91",
    "name": "رطب سكري",
    "category": "dates",
    "price": 120,
    "oldPrice": 140,
    "discount": 14,
    "weight": "550 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السعودية",
    "rating": 4.9
  },
  {
    "id": "92",
    "name": "تمر محشي لوز ومغطى بالشوكلاتة",
    "category": "dates",
    "price": 120,
    "oldPrice": 140,
    "discount": 14,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.8
  },
  {
    "id": "93",
    "name": "تمر نجمة سيوة بالمكسرات",
    "category": "dates",
    "price": 200,
    "oldPrice": 240,
    "discount": 17,
    "weight": "800 جم",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.4
  },
  {
    "id": "94",
    "name": "تمر محشو بالكاجو",
    "category": "dates",
    "price": 130,
    "oldPrice": 150,
    "discount": 13,
    "weight": "400 جم",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "السعودية",
    "rating": 4.3
  },
  {
    "id": "95",
    "name": "تمر محشي لوز ومغطس بشوكولاتة الاسبريسو",
    "category": "dates",
    "price": 120,
    "oldPrice": 140,
    "discount": 14,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.7
  },
  {
    "id": "96",
    "name": "عجوة مفرومة بدون نوى",
    "category": "dates",
    "price": 50,
    "oldPrice": 70,
    "discount": 29,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.1
  },
  {
    "id": "97",
    "name": "تمور نجمة سيوة",
    "category": "dates",
    "price": 0,
    "oldPrice": 0,
    "discount": 0,
    "weight": "multi",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": false,
    "origin": "",
    "rating": 4.5
  },
  {
    "id": "98",
    "name": "تمور نجمة سيوة محشي باللوز",
    "category": "dates",
    "price": 200,
    "oldPrice": 240,
    "discount": 17,
    "weight": "800 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.7
  },
  {
    "id": "99",
    "name": "تمر محشي لوز ومغطس في الشوكلاتة",
    "category": "dates",
    "price": 120,
    "oldPrice": 140,
    "discount": 14,
    "weight": "500 جم",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.4
  },
  {
    "id": "100",
    "name": "تمر الطاقة الطبيعي",
    "category": "dates",
    "price": 150,
    "oldPrice": 180,
    "discount": 17,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 5
  },
  {
    "id": "101",
    "name": "تمر ليبي جالو",
    "category": "dates",
    "price": 70,
    "oldPrice": 100,
    "discount": 30,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/2474669bf8bb49269db7ff67506b3455.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.6
  },
  {
    "id": "102",
    "name": "تمر الوادي علبة",
    "category": "dates",
    "price": 0,
    "oldPrice": 0,
    "discount": 0,
    "weight": "3 كجم",
    "image": "https://karimolive.shop/uploads/products/images/9d9e27c2-dc17-4d72-8ccd-4260326decf1.webp",
    "available": false,
    "origin": "",
    "rating": 4.3
  },
  {
    "id": "103",
    "name": "شاي الأنوثة «الزهورات التركي»",
    "category": "food",
    "price": 120,
    "oldPrice": 150,
    "discount": 20,
    "weight": "200 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.8
  },
  {
    "id": "104",
    "name": "المختوم الفلسطيني الطبيعي لزيادة الوزن",
    "category": "food",
    "price": 250,
    "oldPrice": 350,
    "discount": 29,
    "weight": "500 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.9
  },
  {
    "id": "105",
    "name": "دبس التمر",
    "category": "food",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.3
  },
  {
    "id": "106",
    "name": "صلصة البستان الليبي",
    "category": "food",
    "price": 80,
    "oldPrice": 90,
    "discount": 11,
    "weight": "480 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.7
  },
  {
    "id": "107",
    "name": "خل تفاح عضوي",
    "category": "food",
    "price": 70,
    "oldPrice": 80,
    "discount": 13,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.9
  },
  {
    "id": "108",
    "name": "بخور إماراتي",
    "category": "food",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الإمارات",
    "rating": 4.6
  },
  {
    "id": "109",
    "name": "كركديه سيوي",
    "category": "food",
    "price": 75,
    "oldPrice": 100,
    "discount": 25,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 3.8
  },
  {
    "id": "110",
    "name": "كريم العقرب لتسكين الآلام",
    "category": "food",
    "price": 200,
    "oldPrice": 250,
    "discount": 20,
    "weight": "30 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "نيجيريا",
    "rating": 5
  },
  {
    "id": "111",
    "name": "دهان قلقا لآلام المفاصل",
    "category": "food",
    "price": 140,
    "oldPrice": 180,
    "discount": 22,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "إندونيسيا",
    "rating": 4
  },
  {
    "id": "112",
    "name": "كركديه أسواني فاخر \"لوزة\"",
    "category": "food",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "أسوان",
    "rating": 3.7
  },
  {
    "id": "113",
    "name": "خروب قبرصي أصلي",
    "category": "food",
    "price": 60,
    "oldPrice": 70,
    "discount": 14,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "قبرص",
    "rating": 3.7
  },
  {
    "id": "114",
    "name": "مربى (زيتون / بنجر / باذنجان / برتقال)",
    "category": "food",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "350 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 3.6
  },
  {
    "id": "115",
    "name": "بخور طرابلسي ليبي / بخور الزفة الليبي",
    "category": "food",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.3
  },
  {
    "id": "116",
    "name": "كريم مساج دهن النعام",
    "category": "food",
    "price": 120,
    "oldPrice": 150,
    "discount": 20,
    "weight": "40 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "باكستان",
    "rating": 4.5
  },
  {
    "id": "117",
    "name": "القهوة الخضراء / القهوة العربي السعودي",
    "category": "food",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السعودية",
    "rating": 4.6
  },
  {
    "id": "118",
    "name": "حبهان أخضر",
    "category": "spices",
    "price": 125,
    "oldPrice": 150,
    "discount": 17,
    "weight": "50 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.5
  },
  {
    "id": "119",
    "name": "فلفل أسود",
    "category": "spices",
    "price": 110,
    "oldPrice": 120,
    "discount": 8,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "البرازيل",
    "rating": 4
  },
  {
    "id": "120",
    "name": "كمون بلدي",
    "category": "spices",
    "price": 65,
    "oldPrice": 80,
    "discount": 19,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 3.7
  },
  {
    "id": "121",
    "name": "سماق",
    "category": "spices",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "تركيا",
    "rating": 3.6
  },
  {
    "id": "122",
    "name": "أرز بسمتي طويل الحبة",
    "category": "spices",
    "price": 90,
    "oldPrice": 110,
    "discount": 18,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.4
  },
  {
    "id": "123",
    "name": "بهارات محشي",
    "category": "spices",
    "price": 60,
    "oldPrice": 80,
    "discount": 25,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.9
  },
  {
    "id": "124",
    "name": "مقرمشات كنتاكي",
    "category": "spices",
    "price": 20,
    "oldPrice": 25,
    "discount": 20,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.3
  },
  {
    "id": "125",
    "name": "خلطة كنتاكي",
    "category": "spices",
    "price": 60,
    "oldPrice": 80,
    "discount": 25,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.5
  },
  {
    "id": "126",
    "name": "بهارات التندوري",
    "category": "spices",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.6
  },
  {
    "id": "127",
    "name": "حرارات ليبية",
    "category": "spices",
    "price": 75,
    "oldPrice": 90,
    "discount": 17,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.7
  },
  {
    "id": "128",
    "name": "مستكة يوناني أصلية",
    "category": "spices",
    "price": 125,
    "oldPrice": 150,
    "discount": 17,
    "weight": "10 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "اليونان",
    "rating": 4.5
  },
  {
    "id": "129",
    "name": "فلفل مطحون",
    "category": "spices",
    "price": 110,
    "oldPrice": 120,
    "discount": 8,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "البرازيل",
    "rating": 4.1
  },
  {
    "id": "130",
    "name": "كمون مطحون",
    "category": "spices",
    "price": 65,
    "oldPrice": 70,
    "discount": 7,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 3.8
  },
  {
    "id": "131",
    "name": "السبع بهارات",
    "category": "spices",
    "price": 50,
    "oldPrice": 75,
    "discount": 33,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.4
  },
  {
    "id": "132",
    "name": "بشاميل بالجبنة",
    "category": "spices",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 3.5
  },
  {
    "id": "133",
    "name": "دوم مجروش",
    "category": "spices",
    "price": 40,
    "oldPrice": 50,
    "discount": 20,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "أسوان",
    "rating": 4.1
  },
  {
    "id": "134",
    "name": "خروب مجروش",
    "category": "spices",
    "price": 40,
    "oldPrice": 50,
    "discount": 20,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "قبرص",
    "rating": 3.7
  },
  {
    "id": "135",
    "name": "كسبرة بلدي",
    "category": "spices",
    "price": 30,
    "oldPrice": 40,
    "discount": 25,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 3.8
  },
  {
    "id": "136",
    "name": "شطة قرون",
    "category": "spices",
    "price": 30,
    "oldPrice": 40,
    "discount": 25,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السودان",
    "rating": 4.1
  },
  {
    "id": "137",
    "name": "قرفة سبجار",
    "category": "spices",
    "price": 45,
    "oldPrice": 50,
    "discount": 10,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "إندونيسيا",
    "rating": 4.2
  },
  {
    "id": "138",
    "name": "زيتون تفاحي",
    "category": "olives",
    "price": 120,
    "oldPrice": 170,
    "discount": 29,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 3.7
  },
  {
    "id": "139",
    "name": "زيتون إسباني",
    "category": "olives",
    "price": 160,
    "oldPrice": 230,
    "discount": 30,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.6
  },
  {
    "id": "140",
    "name": "زيتون كالاماتا أخضر",
    "category": "olives",
    "price": 120,
    "oldPrice": 170,
    "discount": 29,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.3
  },
  {
    "id": "141",
    "name": "كلاماتا دولسي",
    "category": "olives",
    "price": 120,
    "oldPrice": 160,
    "discount": 25,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.3
  },
  {
    "id": "142",
    "name": "كلاماتا يوناني",
    "category": "olives",
    "price": 200,
    "oldPrice": 260,
    "discount": 23,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.2
  },
  {
    "id": "143",
    "name": "زيتون عزيزي",
    "category": "olives",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.6
  },
  {
    "id": "144",
    "name": "زيتون شرائح",
    "category": "olives",
    "price": 140,
    "oldPrice": 180,
    "discount": 22,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 5
  },
  {
    "id": "145",
    "name": "زيت جوز الهند",
    "category": "natural_oils",
    "price": 70,
    "oldPrice": 120,
    "discount": 42,
    "weight": "150 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.7
  },
  {
    "id": "146",
    "name": "زيت الروزماري الخام",
    "category": "natural_oils",
    "price": 155,
    "oldPrice": 190,
    "discount": 18,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.4
  },
  {
    "id": "147",
    "name": "زيت الأرجان المغربي",
    "category": "natural_oils",
    "price": 165,
    "oldPrice": 200,
    "discount": 18,
    "weight": "150 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.7
  },
  {
    "id": "148",
    "name": "زيت السعد",
    "category": "natural_oils",
    "price": 150,
    "oldPrice": 180,
    "discount": 17,
    "weight": "150 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.9
  },
  {
    "id": "149",
    "name": "زيت الجوجوبا",
    "category": "natural_oils",
    "price": 150,
    "oldPrice": 180,
    "discount": 17,
    "weight": "150 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.5
  },
  {
    "id": "150",
    "name": "زيت شجرة الشاي الطبيعي",
    "category": "natural_oils",
    "price": 140,
    "oldPrice": 160,
    "discount": 13,
    "weight": "150 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.4
  },
  {
    "id": "151",
    "name": "زيت القرنفل الطبيعي",
    "category": "natural_oils",
    "price": 140,
    "oldPrice": 160,
    "discount": 13,
    "weight": "150 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.5
  },
  {
    "id": "152",
    "name": "زيت الشطة",
    "category": "natural_oils",
    "price": 120,
    "oldPrice": 140,
    "discount": 14,
    "weight": "150 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.7
  },
  {
    "id": "153",
    "name": "زيت الجنزبيل الطبيعي",
    "category": "natural_oils",
    "price": 135,
    "oldPrice": 150,
    "discount": 10,
    "weight": "150 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.3
  },
  {
    "id": "154",
    "name": "زيت الزعتر / القرفة / البابونج / الفل / الليمون",
    "category": "natural_oils",
    "price": 125,
    "oldPrice": 150,
    "discount": 17,
    "weight": "150 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.5
  },
  {
    "id": "155",
    "name": "زيت الأفوكادو",
    "category": "natural_oils",
    "price": 160,
    "oldPrice": 180,
    "discount": 11,
    "weight": "150 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4
  },
  {
    "id": "156",
    "name": "زيت السدر",
    "category": "natural_oils",
    "price": 140,
    "oldPrice": 150,
    "discount": 7,
    "weight": "150 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.7
  },
  {
    "id": "157",
    "name": "زيت بذور العنب / الحلبة",
    "category": "natural_oils",
    "price": 130,
    "oldPrice": 150,
    "discount": 13,
    "weight": "150 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.6
  },
  {
    "id": "158",
    "name": "زيت الياسمين",
    "category": "natural_oils",
    "price": 135,
    "oldPrice": 150,
    "discount": 10,
    "weight": "150 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4
  },
  {
    "id": "159",
    "name": "زيت نخاع",
    "category": "natural_oils",
    "price": 150,
    "oldPrice": 175,
    "discount": 14,
    "weight": "150 مل",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 5
  },
  {
    "id": "160",
    "name": "عسل كريم برسيم",
    "category": "honey",
    "price": 180,
    "oldPrice": 200,
    "discount": 10,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.4
  },
  {
    "id": "161",
    "name": "طحينة خام",
    "category": "honey",
    "price": 200,
    "oldPrice": 220,
    "discount": 9,
    "weight": "1 كجم",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4
  },
  {
    "id": "162",
    "name": "عسل نحل حبة البركة",
    "category": "honey",
    "price": 140,
    "oldPrice": 180,
    "discount": 22,
    "weight": "500 جم",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.6
  },
  {
    "id": "163",
    "name": "عسل نحل زهرة الموالح",
    "category": "honey",
    "price": 125,
    "oldPrice": 150,
    "discount": 17,
    "weight": "500 جم",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.1
  },
  {
    "id": "164",
    "name": "عسل نحل بالمكسرات",
    "category": "honey",
    "price": 150,
    "oldPrice": 180,
    "discount": 17,
    "weight": "500 جم",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 5
  },
  {
    "id": "165",
    "name": "شمع العسل الطبيعي",
    "category": "honey",
    "price": 150,
    "oldPrice": 180,
    "discount": 17,
    "weight": "500 جم",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4
  },
  {
    "id": "166",
    "name": "طحينة خام (500 جم)",
    "category": "honey",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "500 جم",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.3
  },
  {
    "id": "167",
    "name": "عسل جبلي مر حنون ليبي",
    "category": "honey",
    "price": 500,
    "oldPrice": 600,
    "discount": 17,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 3.9
  },
  {
    "id": "168",
    "name": "عسل نحل حضرموت",
    "category": "honey",
    "price": 500,
    "oldPrice": 650,
    "discount": 23,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "اليمن",
    "rating": 4.7
  },
  {
    "id": "169",
    "name": "عسل نحل سدر جبلي طبيعي",
    "category": "honey",
    "price": 350,
    "oldPrice": 450,
    "discount": 22,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.2
  },
  {
    "id": "170",
    "name": "عسل نحل كريم زهرة برسيم (500 جم)",
    "category": "honey",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "500 جم",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.4
  },
  {
    "id": "171",
    "name": "عسل نحل بالمكسرات المشكلة",
    "category": "honey",
    "price": 150,
    "oldPrice": 180,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/c86690ffcdfb4df999f34d4a14418ba8.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.1
  },
  {
    "id": "172",
    "name": "شاي الغزالين",
    "category": "tea_coffee",
    "price": 140,
    "oldPrice": 150,
    "discount": 7,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.1
  },
  {
    "id": "173",
    "name": "شاي الزردة الليبي الأصلي",
    "category": "tea_coffee",
    "price": 120,
    "oldPrice": 140,
    "discount": 14,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.3
  },
  {
    "id": "174",
    "name": "شاي الغزالين أخضر",
    "category": "tea_coffee",
    "price": 65,
    "oldPrice": 80,
    "discount": 19,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.6
  },
  {
    "id": "175",
    "name": "شاي الزردة الليبي أحمر",
    "category": "tea_coffee",
    "price": 60,
    "oldPrice": 70,
    "discount": 14,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.9
  },
  {
    "id": "176",
    "name": "شاي الوادي أحمر",
    "category": "tea_coffee",
    "price": 100,
    "oldPrice": 125,
    "discount": 20,
    "weight": "225 جم",
    "image": "https://karimolive.shop/uploads/products/images/9d9e27c2-dc17-4d72-8ccd-4260326decf1.webp",
    "available": true,
    "origin": "سريلانكا",
    "rating": 4.5
  },
  {
    "id": "177",
    "name": "شاي العنيزي / الجيد / الوكواك / الديوان",
    "category": "tea_coffee",
    "price": 110,
    "oldPrice": 0,
    "discount": 0,
    "weight": "200 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.4
  },
  {
    "id": "178",
    "name": "شاي الجيد الأخضر (علبة معدن)",
    "category": "tea_coffee",
    "price": 200,
    "oldPrice": 220,
    "discount": 9,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 3.8
  },
  {
    "id": "179",
    "name": "شاي الزهرة الأصلي سيلاني",
    "category": "tea_coffee",
    "price": 120,
    "oldPrice": 140,
    "discount": 14,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سريلانكا",
    "rating": 4.7
  },
  {
    "id": "180",
    "name": "شاي الصحراء أخضر / شاي الصين للرشاقة",
    "category": "tea_coffee",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ليبيا",
    "rating": 4.8
  },
  {
    "id": "181",
    "name": "بن Dallmayr جولد",
    "category": "tea_coffee",
    "price": 110,
    "oldPrice": 150,
    "discount": 27,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "ألمانيا",
    "rating": 4
  },
  {
    "id": "182",
    "name": "بن مورينو Extra Dark",
    "category": "tea_coffee",
    "price": 110,
    "oldPrice": 150,
    "discount": 27,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "إيطاليا",
    "rating": 3.9
  },
  {
    "id": "183",
    "name": "بن لافازا روسا",
    "category": "tea_coffee",
    "price": 110,
    "oldPrice": 150,
    "discount": 27,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "إيطاليا",
    "rating": 4.7
  },
  {
    "id": "184",
    "name": "بن ستاربكس Blonde / House Blend",
    "category": "tea_coffee",
    "price": 110,
    "oldPrice": 150,
    "discount": 27,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "",
    "rating": 3.8
  },
  {
    "id": "185",
    "name": "بن دينزلر الإيطالي",
    "category": "tea_coffee",
    "price": 110,
    "oldPrice": 150,
    "discount": 27,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "إيطاليا",
    "rating": 4.3
  },
  {
    "id": "186",
    "name": "لب أبيض",
    "category": "nuts",
    "price": 95,
    "oldPrice": 100,
    "discount": 5,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محمصة نصر",
    "rating": 4.3
  },
  {
    "id": "187",
    "name": "لب سوري",
    "category": "nuts",
    "price": 60,
    "oldPrice": 0,
    "discount": 0,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محمصة نصر",
    "rating": 4.9
  },
  {
    "id": "188",
    "name": "سوداني أسواني",
    "category": "nuts",
    "price": 60,
    "oldPrice": 0,
    "discount": 0,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محمصة نصر",
    "rating": 4.1
  },
  {
    "id": "189",
    "name": "لب سوبر محمص",
    "category": "nuts",
    "price": 85,
    "oldPrice": 95,
    "discount": 11,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محمصة نصر",
    "rating": 4.5
  },
  {
    "id": "190",
    "name": "كاجو محمص بالزبدة",
    "category": "nuts",
    "price": 125,
    "oldPrice": 150,
    "discount": 17,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "فيتنام",
    "rating": 4.9
  },
  {
    "id": "191",
    "name": "بندق محمص ذهبي / فستق محمص",
    "category": "nuts",
    "price": 125,
    "oldPrice": 150,
    "discount": 17,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "تركيا",
    "rating": 4
  },
  {
    "id": "192",
    "name": "ماكاديميا محمصة فاخرة",
    "category": "nuts",
    "price": 220,
    "oldPrice": 250,
    "discount": 12,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "أستراليا",
    "rating": 3.9
  },
  {
    "id": "193",
    "name": "لوز محمص / عين جمل فاخر",
    "category": "nuts",
    "price": 100,
    "oldPrice": 125,
    "discount": 20,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "",
    "rating": 3.8
  },
  {
    "id": "194",
    "name": "عين جمل بقشره",
    "category": "nuts",
    "price": 75,
    "oldPrice": 90,
    "discount": 17,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "إندونيسيا",
    "rating": 4.3
  },
  {
    "id": "195",
    "name": "لوز أمريكي بقشره",
    "category": "nuts",
    "price": 80,
    "oldPrice": 90,
    "discount": 11,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "أمريكا",
    "rating": 4.2
  },
  {
    "id": "196",
    "name": "زبيب أسود / أحمر / مصري فاخر",
    "category": "nuts",
    "price": 62.5,
    "oldPrice": 0,
    "discount": 0,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.7
  },
  {
    "id": "197",
    "name": "زبيب إيراني فاخر",
    "category": "nuts",
    "price": 0,
    "oldPrice": 0,
    "discount": 0,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": false,
    "origin": "",
    "rating": 4.2
  },
  {
    "id": "198",
    "name": "سدر مطحون طبيعي",
    "category": "henna",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 3.9
  },
  {
    "id": "199",
    "name": "المشاط الأحمر",
    "category": "henna",
    "price": 150,
    "oldPrice": 180,
    "discount": 17,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.6
  },
  {
    "id": "200",
    "name": "حنة المدينة",
    "category": "henna",
    "price": 90,
    "oldPrice": 120,
    "discount": 25,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السعودية",
    "rating": 3.8
  },
  {
    "id": "201",
    "name": "نواة التمر",
    "category": "henna",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 3.8
  },
  {
    "id": "202",
    "name": "الحنة البلدي",
    "category": "henna",
    "price": 60,
    "oldPrice": 80,
    "discount": 25,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مطروح - محل كريم",
    "rating": 4.6
  },
  {
    "id": "203",
    "name": "حنة أظافر جوليشيا الهندية",
    "category": "henna",
    "price": 40,
    "oldPrice": 60,
    "discount": 33,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.6
  },
  {
    "id": "204",
    "name": "حناء فرد طبيعي سوفت للشعر",
    "category": "henna",
    "price": 180,
    "oldPrice": 220,
    "discount": 18,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.1
  },
  {
    "id": "205",
    "name": "حنة جوليشيا للرسم",
    "category": "henna",
    "price": 50,
    "oldPrice": 60,
    "discount": 17,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.9
  },
  {
    "id": "206",
    "name": "حناء إمامي جولد الهندية",
    "category": "henna",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "120 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 3.7
  },
  {
    "id": "207",
    "name": "حنة راني الهندية",
    "category": "henna",
    "price": 30,
    "oldPrice": 0,
    "discount": 0,
    "weight": "",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "",
    "rating": 3.5
  },
  {
    "id": "208",
    "name": "حنة نوبار الهندية",
    "category": "henna",
    "price": 50,
    "oldPrice": 100,
    "discount": 50,
    "weight": "170 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.8
  },
  {
    "id": "209",
    "name": "حنة سوداني أصلية",
    "category": "henna",
    "price": 40,
    "oldPrice": 50,
    "discount": 20,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السودان",
    "rating": 4.3
  },
  {
    "id": "210",
    "name": "بذور اليقطين",
    "category": "herbs",
    "price": 150,
    "oldPrice": 200,
    "discount": 25,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.1
  },
  {
    "id": "211",
    "name": "البربرين",
    "category": "herbs",
    "price": 300,
    "oldPrice": 400,
    "discount": 25,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/4e015918ff0f4d328f326f8d541ee5b4.webp",
    "available": true,
    "origin": "الصين",
    "rating": 4
  },
  {
    "id": "212",
    "name": "بذور الشيا",
    "category": "herbs",
    "price": 50,
    "oldPrice": 70,
    "discount": 29,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "المكسيك",
    "rating": 4.1
  },
  {
    "id": "213",
    "name": "بذور الكتان",
    "category": "herbs",
    "price": 60,
    "oldPrice": 70,
    "discount": 14,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.8
  },
  {
    "id": "214",
    "name": "الشمر / الروزماري",
    "category": "herbs",
    "price": 60,
    "oldPrice": 0,
    "discount": 0,
    "weight": "250 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "",
    "rating": 3.7
  },
  {
    "id": "215",
    "name": "الصمغ العربي",
    "category": "herbs",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "السودان",
    "rating": 4.4
  },
  {
    "id": "216",
    "name": "الينسون النجمي",
    "category": "herbs",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الصين",
    "rating": 3.9
  },
  {
    "id": "217",
    "name": "زهرة البابونج",
    "category": "herbs",
    "price": 35,
    "oldPrice": 50,
    "discount": 30,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 3.5
  },
  {
    "id": "218",
    "name": "حب الرشاد",
    "category": "herbs",
    "price": 35,
    "oldPrice": 50,
    "discount": 30,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 4.4
  },
  {
    "id": "219",
    "name": "قسط هندي",
    "category": "herbs",
    "price": 100,
    "oldPrice": 120,
    "discount": 17,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "الهند",
    "rating": 4.9
  },
  {
    "id": "220",
    "name": "البردقوش",
    "category": "herbs",
    "price": 30,
    "oldPrice": 40,
    "discount": 25,
    "weight": "125 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 3.5
  },
  {
    "id": "221",
    "name": "المورينجا",
    "category": "herbs",
    "price": 35,
    "oldPrice": 50,
    "discount": 30,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "سيوة",
    "rating": 4.2
  },
  {
    "id": "222",
    "name": "الماكا",
    "category": "herbs",
    "price": 80,
    "oldPrice": 100,
    "discount": 20,
    "weight": "10 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "تايوان",
    "rating": 4.7
  },
  {
    "id": "223",
    "name": "سفوف حراز العشبي للرشاقة",
    "category": "herbs",
    "price": 90,
    "oldPrice": 110,
    "discount": 18,
    "weight": "150 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "مصر",
    "rating": 3.8
  },
  {
    "id": "224",
    "name": "ورد محمدي مجفف",
    "category": "herbs",
    "price": 150,
    "oldPrice": 200,
    "discount": 25,
    "weight": "50 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": true,
    "origin": "إيران",
    "rating": 4.2
  },
  {
    "id": "225",
    "name": "بذور الأكبي",
    "category": "herbs",
    "price": 0,
    "oldPrice": 0,
    "discount": 0,
    "weight": "100 جم",
    "image": "https://karimolive.shop/uploads/products/images/d1ecfa82ed114b868cb29411746dd26f.webp",
    "available": false,
    "origin": "",
    "rating": 4.6
  }
];